language: python

python:
  - "2.7"

install:
  - pip install coveralls
  - python setup.py develop easy_install gpsd_format[cli,msgpack,test]

script:
  - nosetests --with-coverage

after_success:
  - coveralls
