language: python
sudo: false

cache:
  directories:
    - ~/.cache/pip

python:
  - 2.7
  - 3.3
  - 3.4

install:
  - pip install -e .\[dev\]

script:
  - py.test tests --cov gpsdio --cov-report term-missing

after_success:
  - coveralls

notifications:
  flowdock:
    secure: sSDUIIuldA7tWGqgexf+nmeC/+Htm97bwcPaZOHv2+/c3jKsxUoMMnwkcT3ChqPTEvqs2pGoAYuSDDOWXYUZTpETmZyfECmSqPdfD9nePdqDCum8Q909jlttJWR4jmMuhToNifXdwIkPjnspnLrnxCj92/9/Nx/9uSo/+JfPfE0=
