language: python
sudo: false

cache:
  directories:
    - ~/.cache/pip

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install cython pip setuptools --upgrade
  - pip install -e .\[dev\] --upgrade

script:
  - py.test tests --cov gpsdio --cov-report term-missing

after_success:
  - coveralls

